linters:
  enable-all: true

issues:
  exclude-dirs-use-default: true
  exclude-dirs:
    - bin/*

linters-settings:
  nestif:
    min-complexity: 5

output:
  formats:
  - format: colored-line-number

run:
  timeout: 10m
