name: Lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  metalinter:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.23'
          cache: false
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.5.0
        with:
          version: latest
          args: --timeout=5m
          working-directory: .
          skip-cache: true 